spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/book/**
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
